intf_libs = # Interface dependencies.

if($config.libtaskflow.cuda)
  import intf_libs += cuda-nvcc%liba{nvcc}

lib{taskflow}: {hxx ixx txx}{**} $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{taskflow}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" \
    ($config.libtaskflow.task_pool       ? -DTF_ENABLE_TASK_POOL :) \
    ($config.libtaskflow.atomic_notifier ? -DTF_ENABLE_ATOMIC_NOTIFIER :)
  cxx.export.libs = $intf_libs
}

if ($cxx.target.system != 'win32-msvc')
{
  cxx.libs += -pthread
  lib{taskflow}: cxx.export.libs += -pthread
}

# Install into the taskflow/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/taskflow/
  install.subdirs = true
}
